// Menu items for Tastey Nepal Restro & Cafe
// Only items available in the provided menu images

export const menuItems = [
  // BEVERAGE
  { name: 'Hot Lemon with Honey', category: 'Beverage', price: 110, image: 'https://loremflickr.com/400/300/drink?lock=1001' },
  { name: 'Hot Lemon', category: 'Beverage', price: 40, image: 'https://loremflickr.com/400/300/drink?lock=1002' },
  { name: 'Black Tea', category: 'Beverage', price: 25, image: 'https://loremflickr.com/400/300/tea?lock=1003' },
  { name: 'Milk Tea', category: 'Beverage', price: 30, image: 'https://loremflickr.com/400/300/tea?lock=1004' },
  { name: 'Lemon Tea', category: 'Beverage', price: 35, image: 'https://loremflickr.com/400/300/tea?lock=1005' },
  { name: 'Milk Coffee/Latte', category: 'Beverage', price: 135, image: 'https://loremflickr.com/400/300/coffee?lock=1006' },
  { name: 'Honey Latte', category: 'Beverage', price: 100, image: 'https://loremflickr.com/400/300/drink?lock=1007' },
  { name: 'Café Mocha', category: 'Beverage', price: 100, image: 'https://loremflickr.com/400/300/drink?lock=1008' },
  { name: 'Double Espresso', category: 'Beverage', price: 200, image: 'https://loremflickr.com/400/300/drink?lock=1009' },
  { name: 'Black Coffee/Americano', category: 'Beverage', price: 100, image: 'https://loremflickr.com/400/300/coffee?lock=1010' },
  { name: 'Hot Chocolate', category: 'Beverage', price: 100, image: 'https://loremflickr.com/400/300/drink?lock=1011' },
  // COLD BEVERAGE
  { name: 'Lemonade', category: 'Cold Beverage', price: 100, image: 'https://loremflickr.com/400/300/drink?lock=1012' },
  { name: 'Mint Lemonade', category: 'Cold Beverage', price: 140, image: 'https://loremflickr.com/400/300/drink?lock=1013' },
  { name: 'Plain Lassi', category: 'Cold Beverage', price: 120, image: 'https://loremflickr.com/400/300/drink?lock=1014' },
  { name: 'Banana Lassi', category: 'Cold Beverage', price: 120, image: 'https://loremflickr.com/400/300/drink?lock=1015' },
  { name: 'Black Salt Lemonade', category: 'Cold Beverage', price: 100, image: 'https://loremflickr.com/400/300/drink?lock=1016' },
  { name: 'Virgin Mohito', category: 'Cold Beverage', price: 150, image: 'https://loremflickr.com/400/300/drink?lock=1017' },
  { name: 'Mint/Passion Fruit/Strawberry', category: 'Cold Beverage', price: 250, image: 'https://loremflickr.com/400/300/drink?lock=1018' },
  { name: 'Blended Mocha', category: 'Cold Beverage', price: 350, image: 'https://loremflickr.com/400/300/drink?lock=1019' },
  { name: 'Blended Vanilla Mocha', category: 'Cold Beverage', price: 350, image: 'https://loremflickr.com/400/300/drink?lock=1020' },
  { name: 'Milk Shakes', category: 'Cold Beverage', price: 210, image: 'https://loremflickr.com/400/300/drink?lock=1021' },
  { name: 'Add Scoop of Ice-Cream', category: 'Cold Beverage', price: 60, image: 'https://loremflickr.com/400/300/drink?lock=1022' },
  { name: 'Ice Tea (Lemon/Peach)', category: 'Cold Beverage', price: 130, image: 'https://loremflickr.com/400/300/tea?lock=1023' },
  { name: 'Iced Cappuccino', category: 'Cold Beverage', price: 120, image: 'https://loremflickr.com/400/300/drink?lock=1024' },
  { name: 'Iced Americano', category: 'Cold Beverage', price: 120, image: 'https://loremflickr.com/400/300/drink?lock=1025' },
  // BREAKFAST
  { name: 'Omelette, Bread, Sausage, Sauted Potato', category: 'Breakfast', price: 230, image: 'https://loremflickr.com/400/300/omelette,food?lock=1026' },
  { name: 'Omlet', category: 'Breakfast', price: 90, image: 'https://loremflickr.com/400/300/omlet,food?lock=1027' },
  { name: 'Sunnyside Up', category: 'Breakfast', price: 80, image: 'https://loremflickr.com/400/300/sunnyside,food?lock=1028' },
  { name: '2 Sausage', category: 'Breakfast', price: 100, image: 'https://loremflickr.com/400/300/breakfast,food?lock=1029' },
  // SOUP
  { name: 'Veg Soup', category: 'Soup', price: 150, image: 'https://loremflickr.com/400/300/soup?lock=1030' },
  { name: 'Chicken Soup', category: 'Soup', price: 180, image: 'https://loremflickr.com/400/300/chicken,food?lock=1031' },
  { name: 'Veg Hot & Sour Soup', category: 'Soup', price: 200, image: 'https://loremflickr.com/400/300/soup?lock=1032' },
  { name: 'Non-Veg Hot & Sour Soup', category: 'Soup', price: 220, image: 'https://loremflickr.com/400/300/soup?lock=1033' },
  // SALAD
  { name: 'Green Salad', category: 'Salad', price: 150, image: 'https://loremflickr.com/400/300/salad?lock=1034' },
  { name: 'Chicken Salad', category: 'Salad', price: 200, image: 'https://loremflickr.com/400/300/chicken,food?lock=1035' },
  // FRY RICE
  { name: 'Fry Rice (Veg)', category: 'Fry Rice', price: 150, image: 'https://loremflickr.com/400/300/friedrice?lock=1036' },
  { name: 'Fry Rice (Egg)', category: 'Fry Rice', price: 170, image: 'https://loremflickr.com/400/300/friedrice?lock=1037' },
  { name: 'Fry Rice (Buff)', category: 'Fry Rice', price: 180, image: 'https://loremflickr.com/400/300/friedrice?lock=1038' },
  { name: 'Fry Rice (Mix)', category: 'Fry Rice', price: 220, image: 'https://loremflickr.com/400/300/friedrice?lock=1039' },
  // CHOWMEIN
  { name: 'Chowmein (Veg)', category: 'Chowmein', price: 90, image: 'https://loremflickr.com/400/300/chowmein,noodles?lock=1040' },
  { name: 'Chowmein (Egg)', category: 'Chowmein', price: 100, image: 'https://loremflickr.com/400/300/chowmein,noodles?lock=1041' },
  { name: 'Chowmein (Chicken)', category: 'Chowmein', price: 120, image: 'https://loremflickr.com/400/300/chowmein,noodles?lock=1042' },
  { name: 'Chowmein (Buff)', category: 'Chowmein', price: 120, image: 'https://loremflickr.com/400/300/chowmein,noodles?lock=1043' },
  { name: 'Chowmein (Mix)', category: 'Chowmein', price: 120, image: 'https://loremflickr.com/400/300/chowmein,noodles?lock=1044' },
  // MO:MO
  { name: 'Mo:Mo (Veg, Steam)', category: 'Mo:Mo', price: 110, image: 'https://loremflickr.com/400/300/tea?lock=1045' },
  { name: 'Mo:Mo (Chicken, Steam)', category: 'Mo:Mo', price: 140, image: 'https://loremflickr.com/400/300/tea?lock=1046' },
  { name: 'Mo:Mo (Buff, Steam)', category: 'Mo:Mo', price: 120, image: 'https://loremflickr.com/400/300/tea?lock=1047' },
  { name: 'Mo:Mo (Veg, Jhol)', category: 'Mo:Mo', price: 160, image: 'https://loremflickr.com/400/300/momo,dumpling?lock=1048' },
  { name: 'Mo:Mo (Chicken, Jhol)', category: 'Mo:Mo', price: 160, image: 'https://loremflickr.com/400/300/momo,dumpling?lock=1049' },
  { name: 'Mo:Mo (Buff, Jhol)', category: 'Mo:Mo', price: 160, image: 'https://loremflickr.com/400/300/momo,dumpling?lock=1050' },
  { name: 'Mo:Mo (Veg, Chilly)', category: 'Mo:Mo', price: 160, image: 'https://loremflickr.com/400/300/momo,dumpling?lock=1051' },
  { name: 'Mo:Mo (Chicken, Chilly)', category: 'Mo:Mo', price: 190, image: 'https://loremflickr.com/400/300/momo,dumpling?lock=1052' },
  { name: 'Mo:Mo (Buff, Chilly)', category: 'Mo:Mo', price: 180, image: 'https://loremflickr.com/400/300/momo,dumpling?lock=1053' },
  { name: 'Mo:Mo (Veg, Kothey)', category: 'Mo:Mo', price: 160, image: 'https://loremflickr.com/400/300/momo,dumpling?lock=1054' },
  { name: 'Mo:Mo (Chicken, Kothey)', category: 'Mo:Mo', price: 180, image: 'https://loremflickr.com/400/300/momo,dumpling?lock=1055' },
  { name: 'Mo:Mo (Buff, Kothey)', category: 'Mo:Mo', price: 170, image: 'https://loremflickr.com/400/300/momo,dumpling?lock=1056' },
  // XOILA MO:MO
  { name: 'XOILA MO:MO (Veg)', category: 'XOILA MO:MO', price: 160, image: 'https://loremflickr.com/400/300/momo,dumpling?lock=1057' },
  { name: 'XOILA MO:MO (Chicken)', category: 'XOILA MO:MO', price: 180, image: 'https://loremflickr.com/400/300/momo,dumpling?lock=1058' },
  { name: 'XOILA MO:MO (Buff)', category: 'XOILA MO:MO', price: 170, image: 'https://loremflickr.com/400/300/momo,dumpling?lock=1059' },
  // BURGER & SANDWICH WITH FRIES
  { name: 'Burger & Sandwich with Fries (Veg/with Cheese)', category: 'Burger & Sandwich', price: 180, image: 'https://loremflickr.com/400/300/burger?lock=1060' },
  { name: 'Burger & Sandwich with Fries (Crispy Chicken)', category: 'Burger & Sandwich', price: 250, image: 'https://loremflickr.com/400/300/burger?lock=1061' },
  // PIZZA
  { name: 'Margarita Pizza', category: 'Pizza', price: 400, image: 'https://loremflickr.com/400/300/pizza?lock=1062' },
  { name: 'Smokey Chicken', category: 'Pizza', price: 450, image: 'https://loremflickr.com/400/300/chicken,food?lock=1063' },
  { name: 'Veg Lover', category: 'Pizza', price: 450, image: 'https://loremflickr.com/400/300/veg,food?lock=1064' },
  { name: 'Meat Lover', category: 'Pizza', price: 500, image: 'https://loremflickr.com/400/300/meat,food?lock=1065' },
  { name: 'Add Extra Cheese for Pizza', category: 'Pizza', price: 100, image: 'https://loremflickr.com/400/300/pizza?lock=1066' },
  { name: 'Minced Chicken/Buff', category: 'Pizza', price: 450, image: 'https://loremflickr.com/400/300/chicken,food?lock=1067' },
  // KEEMA NOODLE
  { name: 'Keema Noodle (Veg)', category: 'Keema Noodle', price: 150, image: 'https://loremflickr.com/400/300/keema,food?lock=1068' },
  { name: 'Keema Noodle (Chicken)', category: 'Keema Noodle', price: 180, image: 'https://loremflickr.com/400/300/chicken,food?lock=1069' },
  { name: 'Keema Noodle (Buff)', category: 'Keema Noodle', price: 170, image: 'https://loremflickr.com/400/300/keema,food?lock=1070' },
  // XOILA
  { name: 'XOILA (Chicken)', category: 'XOILA', price: 300, image: 'https://loremflickr.com/400/300/chicken,food?lock=1071' },
  { name: 'XOILA (Buff)', category: 'XOILA', price: 320, image: 'https://loremflickr.com/400/300/xoila,food?lock=1072' },
  // KATHI ROLL
  { name: 'Kathi Roll (Veg/with Cheese)', category: 'Kathi Roll', price: 120, image: 'https://loremflickr.com/400/300/kathi,food?lock=1073' },
  { name: 'Kathi Roll (Chicken/with Cheese)', category: 'Kathi Roll', price: 140, image: 'https://loremflickr.com/400/300/chicken,food?lock=1074' },
  { name: 'Kathi Roll (Pork/with Cheese)', category: 'Kathi Roll', price: 190, image: 'https://loremflickr.com/400/300/kathi,food?lock=1075' },
  // THUKPA
  { name: 'Thukpa (Veg)', category: 'Thukpa', price: 150, image: 'https://loremflickr.com/400/300/thukpa,food?lock=1076' },
  { name: 'Thukpa (Chicken)', category: 'Thukpa', price: 170, image: 'https://loremflickr.com/400/300/chicken,food?lock=1077' },
  { name: 'Thukpa (Buff)', category: 'Thukpa', price: 170, image: 'https://loremflickr.com/400/300/thukpa,food?lock=1078' },
  { name: 'Thukpa (Mix)', category: 'Thukpa', price: 230, image: 'https://loremflickr.com/400/300/thukpa,food?lock=1079' },
  // NON-VEG SNACKS
  { name: 'Chicken Roast', category: 'Non-Veg Snacks', price: 350, image: 'https://loremflickr.com/400/300/chicken,food?lock=1080' },
  { name: 'Mustang Aalu', category: 'Non-Veg Snacks', price: 250, image: 'https://loremflickr.com/400/300/mustang,food?lock=1081' },
  { name: 'Bhatmas Sandeko', category: 'Non-Veg Snacks', price: 250, image: 'https://loremflickr.com/400/300/bhatmas,food?lock=1082' },
  { name: 'Crispy Corn', category: 'Non-Veg Snacks', price: 250, image: 'https://loremflickr.com/400/300/crispy,food?lock=1083' },
  { name: 'Veg/Non-Veg Corn Dog', category: 'Non-Veg Snacks', price: 300, image: 'https://loremflickr.com/400/300/vegnonveg,food?lock=1084' },
  { name: 'Chicken Chilly', category: 'Non-Veg Snacks', price: 380, image: 'https://loremflickr.com/400/300/chicken,food?lock=1085' },
  { name: 'Buff Chilly', category: 'Non-Veg Snacks', price: 380, image: 'https://loremflickr.com/400/300/buff,food?lock=1086' },
  { name: 'Pork Chilly', category: 'Non-Veg Snacks', price: 400, image: 'https://loremflickr.com/400/300/pork,food?lock=1087' },
  { name: 'Sausage Chilly', category: 'Non-Veg Snacks', price: 300, image: 'https://loremflickr.com/400/300/sausage,food?lock=1088' },
  { name: 'Chips Chilly', category: 'Non-Veg Snacks', price: 250, image: 'https://loremflickr.com/400/300/chips,food?lock=1089' },
  { name: 'Sukuti Plus', category: 'Non-Veg Snacks', price: 300, image: 'https://loremflickr.com/400/300/sukuti,food?lock=1090' },
  { name: 'Buff Sukuti Sandeko', category: 'Non-Veg Snacks', price: 300, image: 'https://loremflickr.com/400/300/buff,food?lock=1091' },
  { name: 'Drum stick/Hot Garlic Wings', category: 'Non-Veg Snacks', price: 300, image: 'https://loremflickr.com/400/300/drum,food?lock=1092' },
  { name: 'Chau-Chau Sandeko', category: 'Non-Veg Snacks', price: 160, image: 'https://loremflickr.com/400/300/chauchau,food?lock=1093' },
  { name: 'Chicken Sandeko', category: 'Non-Veg Snacks', price: 160, image: 'https://loremflickr.com/400/300/chicken,food?lock=1094' },
  { name: 'French Fries', category: 'Non-Veg Snacks', price: 170, image: 'https://loremflickr.com/400/300/french,food?lock=1095' },
  // SEKUWA KHAJA SET
  { name: 'Sekuwa Khaja Set (Pork)', category: 'Sekuwa Khaja Set', price: 350, image: 'https://loremflickr.com/400/300/sekuwa,food?lock=1096' },
  { name: 'Sekuwa Khaja Set (Chicken)', category: 'Sekuwa Khaja Set', price: 350, image: 'https://loremflickr.com/400/300/chicken,food?lock=1097' },
  { name: 'Sekuwa Khaja Set (Buff)', category: 'Sekuwa Khaja Set', price: 320, image: 'https://loremflickr.com/400/300/sekuwa,food?lock=1098' },
  // SEKUWA
  { name: 'Sekuwa (Pork, 500g)', category: 'Sekuwa', price: 600, image: 'https://loremflickr.com/400/300/sekuwa,food?lock=1099' },
  { name: 'Sekuwa (Pork, 1kg)', category: 'Sekuwa', price: 1100, image: 'https://loremflickr.com/400/300/sekuwa,food?lock=1100' },
  { name: 'Sekuwa (Chicken, 500g)', category: 'Sekuwa', price: 500, image: 'https://loremflickr.com/400/300/chicken,food?lock=1101' },
  { name: 'Sekuwa (Chicken, 1kg)', category: 'Sekuwa', price: 900, image: 'https://loremflickr.com/400/300/chicken,food?lock=1102' },
  { name: 'Sekuwa (Buff, 500g)', category: 'Sekuwa', price: 500, image: 'https://loremflickr.com/400/300/sekuwa,food?lock=1103' },
  { name: 'Sekuwa (Buff, 1kg)', category: 'Sekuwa', price: 900, image: 'https://loremflickr.com/400/300/sekuwa,food?lock=1104' },
  // CHOPSEUY
  { name: 'Chopseuy (Veg/Non American)', category: 'Chopseuy', price: 230, image: 'https://loremflickr.com/400/300/chopseuy,food?lock=1105' },
  { name: 'Chopseuy (Veg/Non Chinese)', category: 'Chopseuy', price: 230, image: 'https://loremflickr.com/400/300/chopseuy,food?lock=1106' },
  { name: 'Chopseuy (Veg/Non Nasi Goreng)', category: 'Chopseuy', price: 260, image: 'https://loremflickr.com/400/300/chopseuy,food?lock=1107' },
  // COMBO PLATTER
  { name: 'Combo Platter', category: 'Combo Platter', price: 550, image: 'https://loremflickr.com/400/300/combo,food?lock=1108' },
  // COLD DRINKS
  { name: 'Pepsi/Dew/Mirinda/Dew/Slice', category: 'Cold Drinks', price: 70, image: 'https://loremflickr.com/400/300/pepsidewmirindadewslice,food?lock=1109' },
  { name: 'Lemon Soda', category: 'Cold Drinks', price: 70, image: 'https://loremflickr.com/400/300/lemon,food?lock=1110' },
  { name: 'Seasonal Fresh Juice', category: 'Cold Drinks', price: 270, image: 'https://loremflickr.com/400/300/seasonal,food?lock=1111' },
  { name: 'Red Bull', category: 'Cold Drinks', price: 270, image: 'https://loremflickr.com/400/300/red,food?lock=1112' },
  { name: 'Big Max Tiger', category: 'Cold Drinks', price: 150, image: 'https://loremflickr.com/400/300/big,food?lock=1113' },
  { name: 'Extreme', category: 'Cold Drinks', price: 160, image: 'https://loremflickr.com/400/300/extreme,food?lock=1114' },
  // BEER
  { name: 'Nepal Ice', category: 'Beer', price: 450, image: 'https://loremflickr.com/400/300/beer?lock=1115' },
  { name: 'Gorkha Strong Big', category: 'Beer', price: 570, image: 'https://loremflickr.com/400/300/beer?lock=1116' },
  { name: 'Gorkha Strong Small', category: 'Beer', price: 275, image: 'https://loremflickr.com/400/300/beer?lock=1117' },
  { name: 'Tuborg', category: 'Beer', price: 525, image: 'https://loremflickr.com/400/300/beer?lock=1118' },
  // HARD DRINKS
  { name: '8848 Vodka (Qtr)', category: 'Hard Drinks', price: 750, image: 'https://loremflickr.com/400/300/liquor?lock=1119' },
  { name: '8848 Vodka (Half)', category: 'Hard Drinks', price: 1400, image: 'https://loremflickr.com/400/300/liquor?lock=1120' },
  { name: '8848 Vodka (Full)', category: 'Hard Drinks', price: 2750, image: 'https://loremflickr.com/400/300/liquor?lock=1121' },
  { name: 'Golden Oak (Qtr)', category: 'Hard Drinks', price: 400, image: 'https://loremflickr.com/400/300/liquor?lock=1122' },
  { name: 'Golden Oak (Half)', category: 'Hard Drinks', price: 750, image: 'https://loremflickr.com/400/300/liquor?lock=1123' },
  { name: 'Golden Oak (Full)', category: 'Hard Drinks', price: 1400, image: 'https://loremflickr.com/400/300/liquor?lock=1124' },
  { name: 'Khukuri Rum (Qtr)', category: 'Hard Drinks', price: 750, image: 'https://loremflickr.com/400/300/liquor?lock=1125' },
  { name: 'Khukuri Rum (Half)', category: 'Hard Drinks', price: 1400, image: 'https://loremflickr.com/400/300/liquor?lock=1126' },
  { name: 'Khukuri Rum (Full)', category: 'Hard Drinks', price: 2750, image: 'https://loremflickr.com/400/300/liquor?lock=1127' },
  { name: 'Old Durbar (Qtr)', category: 'Hard Drinks', price: 900, image: 'https://loremflickr.com/400/300/liquor?lock=1128' },
  { name: 'Old Durbar (Half)', category: 'Hard Drinks', price: 1750, image: 'https://loremflickr.com/400/300/liquor?lock=1129' },
  { name: 'Old Durbar (Full)', category: 'Hard Drinks', price: 3500, image: 'https://loremflickr.com/400/300/liquor?lock=1130' },
  { name: 'Signature (Qtr)', category: 'Hard Drinks', price: 850, image: 'https://loremflickr.com/400/300/liquor?lock=1131' },
  { name: 'Signature (Half)', category: 'Hard Drinks', price: 1600, image: 'https://loremflickr.com/400/300/liquor?lock=1132' },
  { name: 'Signature (Full)', category: 'Hard Drinks', price: 3100, image: 'https://loremflickr.com/400/300/liquor?lock=1133' },
  { name: 'Ruslan Vodka (Qtr)', category: 'Hard Drinks', price: 800, image: 'https://loremflickr.com/400/300/liquor?lock=1134' },
  { name: 'Ruslan Vodka (Half)', category: 'Hard Drinks', price: 1500, image: 'https://loremflickr.com/400/300/liquor?lock=1135' },
  { name: 'Ruslan Vodka (Full)', category: 'Hard Drinks', price: 2850, image: 'https://loremflickr.com/400/300/liquor?lock=1136' },
  // HUKKA
  { name: 'Hukka (Mint/Double Apple/Blue Berry)', category: 'Hukka', price: 350, image: 'https://loremflickr.com/400/300/hukka,food?lock=1137' },
  { name: 'Hukka (Big Normal)', category: 'Hukka', price: 350, image: 'https://loremflickr.com/400/300/hukka,food?lock=1138' },
  { name: 'Hukka (Cloud)', category: 'Hukka', price: 450, image: 'https://loremflickr.com/400/300/hukka,food?lock=1139' },
];
